# Generated by Django 5.1.2 on 2024-10-27 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'libreria_editorial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=70)),
                ('paginas', models.PositiveIntegerField()),
                ('fecha_publicacion', models.DateField(null=True)),
                ('imagen', models.URLField(max_length=85, null=True)),
                ('desc_corta', models.CharField(max_length=2000)),
                ('estatus', models.CharField(max_length=1)),
                ('categoria', models.CharField(max_length=50)),
                ('edicion_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ediciones_posteriores', to='Orm_Pdf.libro')),
                ('editorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='Orm_Pdf.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='LibroCronica',
            fields=[
                ('descripcion_larga', models.TextField(null=True)),
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Orm_Pdf.libro')),
            ],
        ),
        migrations.CreateModel(
            name='AutorCapitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_capitulos', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orm_Pdf.autor')),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orm_Pdf.libro')),
            ],
            options={
                'db_table': 'autor_capitulo',
            },
        ),
        migrations.AddField(
            model_name='autor',
            name='libros',
            field=models.ManyToManyField(related_name='autores', through='Orm_Pdf.AutorCapitulo', to='Orm_Pdf.libro'),
        ),
    ]
