# Generated by Django 5.1.2 on 2024-10-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orm_Pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(related_name='libros_autores', to='Orm_Pdf.autor'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='libros',
            field=models.ManyToManyField(related_name='libros_de_autor', through='Orm_Pdf.AutorCapitulo', to='Orm_Pdf.libro'),
        ),
    ]
