# Generated by Django 5.1.2 on 2024-10-27 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orm_Pdf', '0002_libro_autores_alter_autor_libros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='libros',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='edicion_anterior',
        ),
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_libros', to='Orm_Pdf.autor')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro_autores', to='Orm_Pdf.libro')),
            ],
        ),
    ]
